### PR TITLE
New JSB-Sim FDM

### PR DESCRIPTION
**Pull request by xcvb85**

### CODE REVIEW

**Comment by FGDATA** [comment]
@lastmin-II  

@xcvb85  had just pushed a new FDM for the Tu-134. I think you are among our most interested users in this tupolev, and one with more experience to judge the pertinence. 

I merged in. Let me know if its cool to stay ;)

@xcvb85 : I;ll send you and invitation to join the FGMEMBERS team

IH-COL

**Comment by lastmin-II** [comment]
I tested the new FDM, and it looks good. I only have some notes:

1) There are stability problems when using the autopilot in altitude hold mode, which I didn't see in the YASim model. The plane slowly starts to oscillate around the lateral axis (pitching up and down). Unfortunately the instability is divergent: if manual control is not resumed by the pilot, the oscillations grow (causing loads between -1 and +3 G) until the plane eventually stalls and sinks into an uncontrollable flight. I experienced this at FL300, which sounds like very reasonable for cruising (the Tu-134 service ceiling is around 39000ft) but the same seem to happen at lower altitudes as well (FL180 and 200). I'm not sure if this is an issue related to the new FDM or to the autopilot.

2) There is no vacuum anymore for the heading indicator and ADF.

3) The N2 tachometer doesn't work anymore.

Both 2) and 3) are related to the engines rpm values, which are absent in the new JSB model. The YASim model generates engine behavior through the "engines-yasim.nas" file.

4) After looking briefly at other models which have both JSB and YAsin FDMs, I suggest that we clearly identify the available Tu-134 models after the FDM they use. At the current state we would have something like this:

> Tu-134-yasim
> Tu-134a-jsbsim

Best,
lastmin

**Comment by IAHM-COL** [comment]
Thanks Lastmin for your continuing work on the Tupolev :)

Looking good

I totally agree with you, that 2 set files to manage the versions for JSB
and Yasim would be a good way to balance the situation. Renaming as you suggested is much more intuitive for someone less familiar with this one project ;)

I wonder if @xcvb85 can look into the issue with the instruments you
mentioned with the newest JSB aero.

Best
@IAHM-COL

**Comment by xcvb85** [comment]
Hi,

@lastmin-II: 
1.) Should be solved now
2./3.) This can have two reasons:
- jsm and yasim use different paths for some variables
- tu134a still lacks some of the systems because they are annoying if you work on the fdm
  I will investigate into this to see what's wrong.
  4.) I don't really care about the name but my main intention is to have a tu134a for the great navigator view. It would be quite strange if you introduce this in the tu134 where you can sit in the nose without windows.

@IAHM-COL: I will have a look.

BR
xcvb

**Pull request merged**
